# Generated by Django 2.1.2 on 2018-10-20 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Cake',
                'verbose_name_plural': 'Cakes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25, verbose_name='Category')),
                ('image', models.ImageField(upload_to='', verbose_name='Image category')),
                ('order', models.PositiveIntegerField(default='', verbose_name='Output order')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=25, verbose_name='Name client')),
                ('review', models.TextField(max_length=500, verbose_name='Review')),
                ('icon', models.ImageField(upload_to='', verbose_name='User icon')),
                ('order', models.PositiveIntegerField(verbose_name='Output order')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Stuffing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Title')),
                ('desc', models.TextField(max_length=500, verbose_name='Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Slide image')),
                ('new', models.BooleanField(default=False, verbose_name='New')),
                ('order', models.PositiveIntegerField(verbose_name='Output order')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Stuffing',
            },
        ),
        migrations.AddField(
            model_name='cake',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='torticapp.Category'),
        ),
    ]
