# Generated by Django 2.1.2 on 2018-10-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torticapp', '0002_stuffing_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(default='', max_length=255, verbose_name='Link'),
        ),
    ]
