# Generated by Django 2.1.2 on 2018-10-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torticapp', '0006_stuffing'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuffing',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Stuffing'),
        ),
    ]
